name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - feature/jobs-page-optimisation  # Here source code branch is `feature/jobs-page-optimisation`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with: { node-version: '12.x' }

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Bundle install
        run: bundle install

      - name: Build Jobs markdown files
        run: bundle exec jekyll pagemaster jobs

      - name: Jekyll site build
        run: bundle exec jekyll build

      - name: "Deploy to feature/jobs-page-optimisation 🚀"
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: feature/jobs-page-optimisation
          FOLDER: _site