# Name of this workflow
name: Google & Yandex Sitemap Notification

# Controls when the action will run:
on:
  # Triggers the workflow on push events, only on the master branch, and only
  # if sitemap.xml was updated:
  push:
    # If your primary ("production") branch is "main" (or anything else) instead
    # of "master" you will need to update this line:
    branches: [ gh-pages ]
    # filepath/s to the updated directories / files that have been committed to your GitHub repo:
    paths:
      - sitemap.xml
      - _posts/*.md
      - _jobPosts/*.md
      - pages/*.md

  # This allows you to run this workflow manually from the Actions tab in your
  # GitHub repo:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel:
jobs:
  # This workflow contains a single job called "pingA" - (the ID for this job):
  pingA:
    # This can be whatever name you like:
    name: Ping Google
    # The type of runner that the job will run on:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the
    # job:
    steps:
      # Runs a single command using the runners shell:
      - name: Send HTTP GET request to Google
        run: curl https://www.google.com/ping?sitemap=https://uxbri.org/sitemap.xml

  # This workflow contains a single job called "pingB" - (the ID for this job):
  pingB:
    # This can be whatever name you like:
    name: Ping Yandex
    # The type of runner that the job will run on:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the
    # job:
    steps:
      # Runs a single command using the runners shell:
      - name: Send HTTP GET request to Yandex
        run: curl https://webmaster.yandex.ru/ping?sitemap=https://uxbri.org/sitemap.xml
